language: csharp
dist: trusty
solution: "./TravisCISampleIntegration/TravisCISampleIntegration.sln"
script:
  - xbuild /p:Configuration=Release "./TravisCISampleIntegration/TravisCISampleIntegration.sln"
  - mono ./TravisCISampleIntegration/packages/xunit.runner.console*/tools/net452/xunit.console.exe ./TravisCISampleIntegration/TravisCISampleIntegration/SumUtils.Test/bin/Release/SumUtils.Test.dll
