language: csharp
solution: "./TravisCISampleIntegration/TravisCISampleIntegration.sln"
script:
  - xbuild /p:Configuration=Release "./TravisCISampleIntegration/TravisCISampleIntegration.sln"
  - mono ./TravisCISampleIntegration/NUnit.Runners.2.6.4/tools/nunit-console.exe ./TravisCISampleIntegration/bin/Release/TravisCISampleIntegration.dll
